# Generated by Django 4.2.16 on 2024-10-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='name',
        ),
    ]
