# Generated by Django 4.2.16 on 2024-10-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_remove_csvfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
